# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  lane :beta do
	  match(git_url: "https://theatlantagoat@bitbucket.org/theatlantagoat/myfastlanekeysnostalgia.git",
      type: "development",
      app_identifier: "com.cosmicarrows.Nostalgia")
      pem
          # gym
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end
  lane :codeSigning do
        match(app_identifier:["com.cosmicarrows.Nostalgia"])
  end
  lane :development do
  register_devices(devices_file: "devices.txt")
  match(type: "development", force_for_new_devices: false)
  end
  lane :release do
    produce(
    username: "laurence@cosmicarrows.com",
    app_identifier: "com.cosmicarrows.Nostalgia",
    app_name: "Nostalgic",
    language: "English",
    app_version: "1.0",
    team_name: "Laurence Wingo" # only necessary when in multiple teams
    )
  end
end
